{{- if .Values.backend.enabled }}
{{- $component := "backend" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "benchfinity.componentName" (dict "context" . "component" $component) }}
  labels:
    {{- include "benchfinity.componentLabels" (dict "context" . "component" $component) | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.containerPort }}
      protocol: TCP
  selector:
    {{- include "benchfinity.componentSelectorLabels" (dict "context" . "component" $component) | nindent 4 }}
{{- end }}
