# GitHub release note generation.
changelog:
  exclude:
    labels:
      - ignore-for-release
      - duplicate
      - invalid
    authors:
      - dependabot
      - dependabot[bot]
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
        - breaking
    - title: Features
      labels:
        - enhancement
        - feature
    - title: Fixes
      labels:
        - bug
        - fix
    - title: CI and Release
      labels:
        - ci
        - release
        - docker
    - title: Documentation
      labels:
        - documentation
        - docs
    - title: Dependencies
      labels:
        - dependencies
    - title: Other Changes
      labels:
        - "*"
