import { BufferGeometry, Matrix4, Vector3 } from "three";
import type { GeometryPart } from "../geometry/types";

type BinaryStlOptions = {
  rotationDeg?: number;
};

type Triangle = {
  a: Vector3;
  b: Vector3;
  c: Vector3;
  normal: Vector3;
};

export function serializeBinaryStl(parts: GeometryPart[], solidName: string, options: BinaryStlOptions = {}): Blob {
  return new Blob([serializeBinaryStlBuffer(parts, solidName, options)], { type: "model/stl" });
}

export function serializeBinaryStlBuffer(
  parts: GeometryPart[],
  solidName: string,
  options: BinaryStlOptions = {},
): ArrayBuffer {
  const transform = createZRotationMatrix(options.rotationDeg ?? 0);
  const triangles = parts.flatMap((part) => trianglesFromGeometry(part.geometry, transform));
  const buffer = new ArrayBuffer(84 + triangles.length * 50);
  const view = new DataView(buffer);
  const header = new TextEncoder().encode(`Generated by Benchfinity: ${solidName}`);

  new Uint8Array(buffer, 0, Math.min(header.length, 80)).set(header.slice(0, 80));
  view.setUint32(80, triangles.length, true);

  triangles.forEach((triangle, index) => {
    const offset = 84 + index * 50;
    writeVector(view, offset, triangle.normal);
    writeVector(view, offset + 12, triangle.a);
    writeVector(view, offset + 24, triangle.b);
    writeVector(view, offset + 36, triangle.c);
    view.setUint16(offset + 48, 0, true);
  });

  return buffer;
}

function trianglesFromGeometry(geometry: BufferGeometry, matrix = new Matrix4()): Triangle[] {
  const position = geometry.getAttribute("position");
  const index = geometry.getIndex();
  const triangles: Triangle[] = [];
  const a = new Vector3();
  const b = new Vector3();
  const c = new Vector3();

  const addTriangle = (ia: number, ib: number, ic: number) => {
    a.fromBufferAttribute(position, ia).applyMatrix4(matrix);
    b.fromBufferAttribute(position, ib).applyMatrix4(matrix);
    c.fromBufferAttribute(position, ic).applyMatrix4(matrix);

    const normal = new Vector3().subVectors(b, a).cross(new Vector3().subVectors(c, a)).normalize();

    triangles.push({
      a: a.clone(),
      b: b.clone(),
      c: c.clone(),
      normal,
    });
  };

  if (index) {
    for (let i = 0; i < index.count; i += 3) {
      addTriangle(index.getX(i), index.getX(i + 1), index.getX(i + 2));
    }
  } else {
    for (let i = 0; i < position.count; i += 3) {
      addTriangle(i, i + 1, i + 2);
    }
  }

  return triangles;
}

function createZRotationMatrix(rotationDeg: number): Matrix4 {
  return new Matrix4().makeRotationZ((rotationDeg * Math.PI) / 180);
}

function writeVector(view: DataView, offset: number, vector: Vector3): void {
  view.setFloat32(offset, vector.x, true);
  view.setFloat32(offset + 4, vector.y, true);
  view.setFloat32(offset + 8, vector.z, true);
}
