import type { Unit } from "./geometry/types";

export type PrinterPreset = {
  id: string;
  brand: string;
  name: string;
  bedWidth: number;
  bedDepth: number;
  unit: Unit;
  notes?: string;
};

export type PrinterGroup = {
  brand: string;
  presets: PrinterPreset[];
};

export const CUSTOM_PRINTER_ID = "custom";
export const DEFAULT_PRINTER_ID = "bambu-h2c-left";

export const PRINTER_PRESETS: PrinterPreset[] = [
  {
    id: "bambu-h2c-left",
    brand: "Bambu Lab",
    name: "Bambu Lab H2C, left nozzle",
    bedWidth: 325,
    bedDepth: 320,
    unit: "mm",
    notes: "Largest single-nozzle area",
  },
  {
    id: "bambu-h2c-right",
    brand: "Bambu Lab",
    name: "Bambu Lab H2C, right nozzle",
    bedWidth: 305,
    bedDepth: 320,
    unit: "mm",
    notes: "Right toolhead area",
  },
  {
    id: "bambu-h2c-dual-nozzle",
    brand: "Bambu Lab",
    name: "Bambu Lab H2C, dual-nozzle safe",
    bedWidth: 300,
    bedDepth: 320,
    unit: "mm",
    notes: "Reduced multi-nozzle envelope",
  },
  {
    id: "bambu-h2c-total-envelope",
    brand: "Bambu Lab",
    name: "Bambu Lab H2C, total two-nozzle envelope",
    bedWidth: 330,
    bedDepth: 320,
    unit: "mm",
    notes: "Combined envelope, not a single-nozzle-safe preset",
  },
  {
    id: "bambu-h2d-max",
    brand: "Bambu Lab",
    name: "Bambu Lab H2D, total",
    bedWidth: 350,
    bedDepth: 320,
    unit: "mm",
  },
  {
    id: "bambu-h2d-left",
    brand: "Bambu Lab",
    name: "Bambu Lab H2D, single nozzle",
    bedWidth: 325,
    bedDepth: 320,
    unit: "mm",
  },
  {
    id: "bambu-h2d-dual",
    brand: "Bambu Lab",
    name: "Bambu Lab H2D, dual-nozzle safe",
    bedWidth: 300,
    bedDepth: 320,
    unit: "mm",
  },
  {
    id: "bambu-h2s",
    brand: "Bambu Lab",
    name: "Bambu Lab H2S",
    bedWidth: 340,
    bedDepth: 320,
    unit: "mm",
  },
  {
    id: "bambu-x1-p1-a1",
    brand: "Bambu Lab",
    name: "Bambu Lab X1/P1/A1",
    bedWidth: 256,
    bedDepth: 256,
    unit: "mm",
  },
  {
    id: "bambu-a1-mini",
    brand: "Bambu Lab",
    name: "Bambu Lab A1 mini",
    bedWidth: 180,
    bedDepth: 180,
    unit: "mm",
  },
  {
    id: "prusa-mk4",
    brand: "Prusa",
    name: "Prusa MK4/MK4S",
    bedWidth: 250,
    bedDepth: 210,
    unit: "mm",
  },
  {
    id: "prusa-core-one",
    brand: "Prusa",
    name: "Prusa CORE One",
    bedWidth: 250,
    bedDepth: 220,
    unit: "mm",
  },
  {
    id: "prusa-core-one-l",
    brand: "Prusa",
    name: "Prusa CORE One L",
    bedWidth: 300,
    bedDepth: 300,
    unit: "mm",
  },
  {
    id: "prusa-mini",
    brand: "Prusa",
    name: "Prusa MINI+",
    bedWidth: 180,
    bedDepth: 180,
    unit: "mm",
  },
  {
    id: "prusa-xl",
    brand: "Prusa",
    name: "Prusa XL",
    bedWidth: 360,
    bedDepth: 360,
    unit: "mm",
  },
  {
    id: "creality-ender-3",
    brand: "Creality",
    name: "Creality Ender 3 family",
    bedWidth: 220,
    bedDepth: 220,
    unit: "mm",
  },
  {
    id: "creality-ender-3-v3-se",
    brand: "Creality",
    name: "Creality Ender 3 V3 SE",
    bedWidth: 220,
    bedDepth: 220,
    unit: "mm",
  },
  {
    id: "creality-ender-3-v3-ke",
    brand: "Creality",
    name: "Creality Ender 3 V3 KE",
    bedWidth: 220,
    bedDepth: 220,
    unit: "mm",
  },
  {
    id: "creality-ender-3-v3-plus",
    brand: "Creality",
    name: "Creality Ender 3 V3 Plus",
    bedWidth: 300,
    bedDepth: 300,
    unit: "mm",
  },
  {
    id: "creality-k1",
    brand: "Creality",
    name: "Creality K1",
    bedWidth: 220,
    bedDepth: 220,
    unit: "mm",
  },
  {
    id: "creality-k1-max",
    brand: "Creality",
    name: "Creality K1 Max",
    bedWidth: 300,
    bedDepth: 300,
    unit: "mm",
  },
  {
    id: "creality-k2-plus",
    brand: "Creality",
    name: "Creality K2 Plus",
    bedWidth: 350,
    bedDepth: 350,
    unit: "mm",
  },
  {
    id: "creality-cr-10",
    brand: "Creality",
    name: "Creality CR-10 family",
    bedWidth: 300,
    bedDepth: 300,
    unit: "mm",
  },
  {
    id: "creality-cr-m4",
    brand: "Creality",
    name: "Creality CR-M4",
    bedWidth: 450,
    bedDepth: 450,
    unit: "mm",
  },
  {
    id: "anycubic-kobra-2-neo",
    brand: "Anycubic",
    name: "Anycubic Kobra 2 Neo",
    bedWidth: 220,
    bedDepth: 220,
    unit: "mm",
  },
  {
    id: "anycubic-kobra-3",
    brand: "Anycubic",
    name: "Anycubic Kobra 3",
    bedWidth: 250,
    bedDepth: 250,
    unit: "mm",
  },
  {
    id: "anycubic-kobra-2-pro",
    brand: "Anycubic",
    name: "Anycubic Kobra 2 Pro",
    bedWidth: 250,
    bedDepth: 220,
    unit: "mm",
  },
  {
    id: "anycubic-kobra-2-plus",
    brand: "Anycubic",
    name: "Anycubic Kobra 2 Plus",
    bedWidth: 320,
    bedDepth: 320,
    unit: "mm",
  },
  {
    id: "anycubic-kobra-2-max",
    brand: "Anycubic",
    name: "Anycubic Kobra 2 Max",
    bedWidth: 420,
    bedDepth: 420,
    unit: "mm",
  },
  {
    id: "anycubic-kobra-s1",
    brand: "Anycubic",
    name: "Anycubic Kobra S1",
    bedWidth: 250,
    bedDepth: 250,
    unit: "mm",
  },
  {
    id: "elegoo-centauri-carbon",
    brand: "Elegoo",
    name: "Elegoo Centauri Carbon",
    bedWidth: 256,
    bedDepth: 256,
    unit: "mm",
  },
  {
    id: "elegoo-neptune-4",
    brand: "Elegoo",
    name: "Elegoo Neptune 4/4 Pro",
    bedWidth: 225,
    bedDepth: 225,
    unit: "mm",
  },
  {
    id: "elegoo-neptune-4-plus",
    brand: "Elegoo",
    name: "Elegoo Neptune 4 Plus",
    bedWidth: 320,
    bedDepth: 320,
    unit: "mm",
  },
  {
    id: "elegoo-neptune-4-max",
    brand: "Elegoo",
    name: "Elegoo Neptune 4 Max",
    bedWidth: 420,
    bedDepth: 420,
    unit: "mm",
  },
  {
    id: "elegoo-orangestorm-giga",
    brand: "Elegoo",
    name: "Elegoo OrangeStorm Giga",
    bedWidth: 800,
    bedDepth: 800,
    unit: "mm",
  },
  {
    id: "sovol-sv06",
    brand: "Sovol",
    name: "Sovol SV06/SV06 ACE",
    bedWidth: 220,
    bedDepth: 220,
    unit: "mm",
  },
  {
    id: "sovol-sv06-plus",
    brand: "Sovol",
    name: "Sovol SV06 Plus",
    bedWidth: 300,
    bedDepth: 300,
    unit: "mm",
  },
  {
    id: "sovol-sv07",
    brand: "Sovol",
    name: "Sovol SV07",
    bedWidth: 220,
    bedDepth: 220,
    unit: "mm",
  },
  {
    id: "sovol-sv08",
    brand: "Sovol",
    name: "Sovol SV08",
    bedWidth: 350,
    bedDepth: 350,
    unit: "mm",
  },
  {
    id: "qidi-x-plus-3",
    brand: "Qidi",
    name: "Qidi X-Plus 3",
    bedWidth: 280,
    bedDepth: 280,
    unit: "mm",
  },
  {
    id: "qidi-q1-pro",
    brand: "Qidi",
    name: "Qidi Q1 Pro",
    bedWidth: 245,
    bedDepth: 245,
    unit: "mm",
  },
  {
    id: "qidi-plus4",
    brand: "Qidi",
    name: "Qidi Plus4",
    bedWidth: 305,
    bedDepth: 305,
    unit: "mm",
  },
  {
    id: "qidi-x-max-3",
    brand: "Qidi",
    name: "Qidi X-Max 3",
    bedWidth: 325,
    bedDepth: 325,
    unit: "mm",
  },
  {
    id: "flashforge-adventurer-5m",
    brand: "FlashForge",
    name: "FlashForge Adventurer 5M/5M Pro",
    bedWidth: 220,
    bedDepth: 220,
    unit: "mm",
  },
  {
    id: "flashforge-guider-3",
    brand: "FlashForge",
    name: "FlashForge Guider 3",
    bedWidth: 300,
    bedDepth: 250,
    unit: "mm",
  },
  {
    id: "flashforge-creator-4",
    brand: "FlashForge",
    name: "FlashForge Creator 4",
    bedWidth: 400,
    bedDepth: 350,
    unit: "mm",
  },
  {
    id: "ultimaker-2-connect",
    brand: "UltiMaker",
    name: "UltiMaker 2+ Connect",
    bedWidth: 223,
    bedDepth: 220,
    unit: "mm",
  },
  {
    id: "ultimaker-s3",
    brand: "UltiMaker",
    name: "UltiMaker S3",
    bedWidth: 230,
    bedDepth: 190,
    unit: "mm",
  },
  {
    id: "ultimaker-s5-s7",
    brand: "UltiMaker",
    name: "UltiMaker S5/S7",
    bedWidth: 330,
    bedDepth: 240,
    unit: "mm",
  },
  {
    id: "ultimaker-factor-4",
    brand: "UltiMaker",
    name: "UltiMaker Factor 4",
    bedWidth: 330,
    bedDepth: 240,
    unit: "mm",
  },
  {
    id: "raise3d-e2",
    brand: "Raise3D",
    name: "Raise3D E2/E2CF",
    bedWidth: 330,
    bedDepth: 240,
    unit: "mm",
  },
  {
    id: "raise3d-pro3",
    brand: "Raise3D",
    name: "Raise3D Pro3",
    bedWidth: 300,
    bedDepth: 300,
    unit: "mm",
  },
  {
    id: "raise3d-pro3-plus",
    brand: "Raise3D",
    name: "Raise3D Pro3 Plus",
    bedWidth: 300,
    bedDepth: 300,
    unit: "mm",
  },
  {
    id: "raise3d-pro2",
    brand: "Raise3D",
    name: "Raise3D Pro2",
    bedWidth: 305,
    bedDepth: 305,
    unit: "mm",
  },
  {
    id: "lulzbot-mini-2",
    brand: "LulzBot",
    name: "LulzBot Mini 2",
    bedWidth: 160,
    bedDepth: 160,
    unit: "mm",
  },
  {
    id: "lulzbot-taz-6",
    brand: "LulzBot",
    name: "LulzBot TAZ 6",
    bedWidth: 280,
    bedDepth: 280,
    unit: "mm",
  },
  {
    id: "lulzbot-taz",
    brand: "LulzBot",
    name: "LulzBot TAZ Workhorse/Pro",
    bedWidth: 280,
    bedDepth: 280,
    unit: "mm",
  },
  {
    id: "lulzbot-sidekick-289",
    brand: "LulzBot",
    name: "LulzBot SideKick 289",
    bedWidth: 289,
    bedDepth: 289,
    unit: "mm",
  },
  {
    id: "voron-02-120",
    brand: "Voron",
    name: "Voron 0.2, 120",
    bedWidth: 120,
    bedDepth: 120,
    unit: "mm",
  },
  {
    id: "voron-trident-250",
    brand: "Voron",
    name: "Voron Trident, 250",
    bedWidth: 250,
    bedDepth: 250,
    unit: "mm",
  },
  {
    id: "voron-trident-300",
    brand: "Voron",
    name: "Voron Trident, 300",
    bedWidth: 300,
    bedDepth: 300,
    unit: "mm",
  },
  {
    id: "voron-trident-350",
    brand: "Voron",
    name: "Voron Trident, 350",
    bedWidth: 350,
    bedDepth: 350,
    unit: "mm",
  },
  {
    id: "voron-24-300",
    brand: "Voron",
    name: "Voron 2.4, 300",
    bedWidth: 300,
    bedDepth: 300,
    unit: "mm",
  },
  {
    id: "voron-24-250",
    brand: "Voron",
    name: "Voron 2.4, 250",
    bedWidth: 250,
    bedDepth: 250,
    unit: "mm",
  },
  {
    id: "voron-24-350",
    brand: "Voron",
    name: "Voron 2.4, 350",
    bedWidth: 350,
    bedDepth: 350,
    unit: "mm",
  },
  {
    id: "ratrig-vcore-300",
    brand: "RatRig",
    name: "RatRig V-Core, 300",
    bedWidth: 300,
    bedDepth: 300,
    unit: "mm",
  },
  {
    id: "ratrig-vcore-400",
    brand: "RatRig",
    name: "RatRig V-Core, 400",
    bedWidth: 400,
    bedDepth: 400,
    unit: "mm",
  },
  {
    id: "ratrig-vcore-500",
    brand: "RatRig",
    name: "RatRig V-Core, 500",
    bedWidth: 500,
    bedDepth: 500,
    unit: "mm",
  },
];

export function findPrinterPreset(id: string): PrinterPreset | undefined {
  return PRINTER_PRESETS.find((preset) => preset.id === id);
}

export function groupPrintersByBrand(presets: PrinterPreset[] = PRINTER_PRESETS): PrinterGroup[] {
  return presets.reduce<PrinterGroup[]>((groups, preset) => {
    const existing = groups.find((group) => group.brand === preset.brand);

    if (existing) {
      existing.presets.push(preset);
    } else {
      groups.push({
        brand: preset.brand,
        presets: [preset],
      });
    }

    return groups;
  }, []);
}
